// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmdfmm2N_y1OA9VTdtdBiKXMCHjL9RhCw',
    appId: '1:710259264384:web:08844a44a17f9357abcf65',
    messagingSenderId: '710259264384',
    projectId: 'hotelmotel-66527',
    authDomain: 'hotelmotel-66527.firebaseapp.com',
    storageBucket: 'hotelmotel-66527.appspot.com',
    measurementId: 'G-EG6YPM56QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYcHj1LWgucVQNzP_0M_nxn9jmzb_d6Qo',
    appId: '1:710259264384:android:12081121d421f61cabcf65',
    messagingSenderId: '710259264384',
    projectId: 'hotelmotel-66527',
    storageBucket: 'hotelmotel-66527.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqEztT13tH3J3D8ICUntjGnMXpdioWwq0',
    appId: '1:710259264384:ios:add42c9c874da469abcf65',
    messagingSenderId: '710259264384',
    projectId: 'hotelmotel-66527',
    storageBucket: 'hotelmotel-66527.appspot.com',
    iosClientId: '710259264384-39cll7q53e213fvafmsva4rup2ltv5l5.apps.googleusercontent.com',
    iosBundleId: 'pl.makjac.hotelMotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqEztT13tH3J3D8ICUntjGnMXpdioWwq0',
    appId: '1:710259264384:ios:a775d2c23ce397f8abcf65',
    messagingSenderId: '710259264384',
    projectId: 'hotelmotel-66527',
    storageBucket: 'hotelmotel-66527.appspot.com',
    iosClientId: '710259264384-eheudem342hr959gtjhsg0j5luetepe8.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelMotel',
  );
}
